---
####################################################
#          ModuleBuilder Configuration             #
####################################################

CopyPaths:
  - en-US
  - tasks
Encoding: UTF8
VersionedOutputDirectory: true
BuiltModuleSubdirectory: module

AliasesToExport:
  - 'Task.Create_Changelog_PR'
  - 'Task.Create_Release_Git_Tag'

####################################################
#       Sampler Pipeline Configuration             #
####################################################
BuildWorkflow:
  '.':
    - build
    - test

  Add_Aliases_To_Module_Manifest: |
    {
        <#
            This is quick fix for issue https://github.com/PoshCode/ModuleBuilder/issues/103.
            Aliases need to be added to module manifest, and we can only use
            New-Alias or Set-Alias together with build tasks. This module
            already automatically exports aliases using [Alias()] so this quick
            fix is meant as a workaround until the above issue is resolved.
        #>
        param
        (
            $OutputDirectory = (property OutputDirectory (Join-Path $BuildRoot 'output')),
            $ProjectName = (property ProjectName ''),
            $BuildInfo = (property BuildInfo @{ })
        )

         . Set-SamplerTaskVariable

        $existingAliases = @((Test-ModuleManifest -Path $BuiltModuleManifest).ExportedAliases.Values.Name)

        # It was not really an empty collection, without this it added "" as an alias to the manifest below.
        if ([System.String]::IsNullOrEmpty($existingAliases))
        {
            $existingAliases = @()
        }

        "`tAlready Exported Aliases     = {0}" -f ($existingAliases -join ', ')
        "`tAdditional Aliases To Export = {0}" -f ($BuildInfo.AliasesToExport -join ', ')

        Update-Metadata -Path $BuiltModuleManifest -PropertyName AliasesToExport -Value ($existingAliases + $BuildInfo.AliasesToExport)
    }

  build:
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Add_Aliases_To_Module_Manifest
    - Create_changelog_release_output

  pack:
    - build
    - package_module_nupkg

  hqrmtest:
    - Invoke_HQRM_Tests_Stop_On_Fail

  test:
    - Pester_Tests_Stop_On_Fail
    - Convert_Pester_Coverage
    - Pester_if_Code_Coverage_Under_Threshold

  merge:
    - Merge_CodeCoverage_Files

  publish:
    - Publish_release_to_GitHub
    - publish_module_to_gallery

####################################################
#       PESTER  Configuration                      #
####################################################

Pester:
  Configuration:
    Run:
      Path:
        - tests/QA
        - tests/Unit
        - tests/Integration
    CodeCoverage:
      CoveragePercentTarget: 78
      OutputPath: JaCoCo_coverage.xml
      OutputEncoding: ascii
  ExcludeFromCodeCoverage:

CodeCoverage:
  CodeCoverageFilePattern: JaCoCo_Merge.xml # the pattern used to search all pipeline test job artifacts
  CodeCoverageMergedOutputFile: JaCoCo_coverage.xml # the file that is created for the merged code coverage

DscTest:
  Pester:
    Configuration:
      Filter:
        Tag:
        ExcludeTag:
          - Common Tests - New Error-Level Script Analyzer Rules
      Output:
        Verbosity: Detailed
      TestResult:
        Enabled: true
        OutputFormat: NUnitXML
        OutputPath: ./output/testResults/NUnitXml_DscResourceCommon_HQRM.xml
        OutputEncoding: UTF-8
        TestSuiteName: DscResourceCommonHQRM
  Script:
    ExcludeSourceFile:
      - output
      - DscResource.Common
    ExcludeModuleFile:
    MainGitBranch: main

ModuleBuildTasks:
  Sampler:
    - '*.build.Sampler.ib.tasks'
  Sampler.GitHubTasks:
    - '*.ib.tasks'
  DscResource.Test:
    - 'Task.*'

# Invoke-Build Header to be used to 'decorate' the terminal output of the tasks.
TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

GitHubConfig:
  GitHubFilesToAdd:
    - 'CHANGELOG.md'
  #GitHubConfigUserName: dscbot
  #GitHubConfigUserEmail: dsccommunity@outlook.com
  UpdateChangelogOnPrerelease: false
